version: '3'
services:
  mariadb:
    image: 'mariadb:10.6.12'
    container_name: 'mariadbcontainer'
    environment:
      MYSQL_ROOT_PASSWORD: homenet
      MYSQL_DATABASE: gitea
      MYSQL_USER: anna
      MYSQL_PASSWORD: homenet
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:

